# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: batect - run test
        run: ./batect test-all
      - name: build and push image to dockerhub
        run: |
          docker login -u ${{ secrets.dockerhub_username }} -p ${{ secrets.dockerhub_password }}
          docker tag poker-poker-server ${{ secrets.dockerhub_username }}/poker-server:latest
          docker tag poker-poker-client ${{ secrets.dockerhub_username }}/poker-client:latest
          docker images
          docker push ${{ secrets.dockerhub_username }}/poker-server:latest
          docker push ${{ secrets.dockerhub_username }}/poker-client:latest
